create table public.news (
  id bigint generated by default as identity primary key,
  title text not null,
  summary text,
  content text,
  image_url text,
  image_alt text,
  video_url text,
  source_url text,
  sort_key integer not null default 10,
  is_published boolean not null default false,
  created_at timestamptz not null default now()
);

alter table public.news enable row level security;

create policy "Public can read published news"
on public.news
for select
to anon, authenticated
using (is_published = true);
